# Generated by Django 4.2.4 on 2023-09-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'orderline', 'verbose_name_plural': 'orderlines'},
        ),
        migrations.AlterModelOptions(
            name='partservice',
            options={'verbose_name': 'partservice', 'verbose_name_plural': 'partservices'},
        ),
    ]
