# Generated by Django 4.2.4 on 2023-10-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_alter_orderline_options_alter_partservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'order line', 'verbose_name_plural': 'order lines'},
        ),
        migrations.AddField(
            model_name='orderline',
            name='part_service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservisas.partservice', verbose_name='part or service'),
            preserve_default=False,
        ),
    ]
