# Generated by Django 4.2.4 on 2023-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_alter_orderline_options_orderline_part_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'service or order', 'verbose_name_plural': 'service or orders'},
        ),
        migrations.AddField(
            model_name='partservice',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
